openapi: 3.0.3
info: 
  title: STD2401
  version: 99.99.0
  description: This is specification of STD24021
servers:
  - url: "http://localhost:800"
paths: 
  /health: 
    get: 
      responses: 
        200: 
          description: return ok
          content:
            text/plain: 
              schema: 
                type: string
                example: ok
  /phones: 
    post: 
        requestBody:
          description: créer une liste de phones
          content:
            application/json: 
              schema: 
                items: 
                  $ref: "#/components/schemas/Phones"
        responses:
          200: 
            description: créer une liste de phones
            content:
              application/json:
                schema: 
                  items: 
                    $ref: "#/components/schemas/Phones"
    get:  
      responses:
        200: 
          description: récperer la memoire de la liste d'objet sauvegardé
          content:
            application/json:
              schema: 
                items: 
                  $ref: "#/components/schemas/Phones"
  /phones/{id}: 
    get: 
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          items: 
             $ref: "#/components/schemas/Phones"
      responses:
        200: 
          description: phone trouvé à l'aide d'un identifiant
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/Phones"

        400: 
          description: 404 not found
          content:
            text/plain:
              schema: 
                type: string
                example: le phone contenant cet id n'existe pas ou n'a pas été retrouvé 
  /phones/{id}/characteristics: 
    put: 
      parameters:
        - in: path
          required: true 
          name: id 
          schema: 
            type: integer
      responses: 
      


components:
  schemas:
    Phones: 
      properties:
        identifier: 
          type: string
        brand: 
          type: string
        model: 
          type: string
        characteristics: 
          properties:
            Characteristics: 
              properties:
                ram_memory: 
                  type: integer
                rom_memory: 
                  type: integer

        

